select * from customer limit 20

---Q1 what is the total revenue generated by male vs female customers 

select gender , sum(purchase_amount)as revenue
from customer
group by gender

----Q2 which customers used a discount but still spent more then avg purchase amount

select customerid,purchase_amount
from customer
where discountapplied ='yes' and purchase_amount>(select AVG(purchase_amount) from customer);

---Q3 which are the top 5 products with the highest average review ratiing

SELECT itempurchased,
       AVG(reviewrating) AS avg_rating,
       COUNT(*) AS reviews
FROM customer
GROUP BY itempurchased
ORDER BY avg_rating DESC
LIMIT 5;

---Q4 compare the average purchase amount between standard and express sgipping

 SELECT 
    shippingtype,
    AVG(purchase_amount) AS avg_purchase_amount
FROM customer
WHERE shippingtype IN ('Standard', 'Express')
GROUP BY shippingtype;

----Q5 do subscribe customer spend more?comapre avg spend and total revenue btw subscriber and non-subscriber


select subscriptionstatus,
count(customerid) as total_customer,
ROUND(AVG(purchase_amount),2)as avg_spend,
ROUND(SUM(purchase_amount),2)as total_revenue
from customer
group by subscriptionstatus
order by total_revenue,avg_spend desc;

---Q6 which 5 product highest percentage of purchases with discount applied?

select itempurchased,
ROUND (100 * SUM(CASE WHEN discountapplied ='yes' THEN 1 ELSE 0 END)/COUNT(*),2) as discount_rate
FROM customer
group by itempurchased
order by discount_rate desc
limit 5;

---Q7 segemet customer into new, returning,and loyal based on there total number of previous
----purchasse,and show the count of each segment

WITH customer_type AS (
  SELECT customerid,
         previouspurchases,
         CASE
           WHEN previouspurchases = 1 THEN 'new'
           WHEN previouspurchases BETWEEN 2 AND 10 THEN 'returning'
           ELSE 'loyal'
         END AS customer_segment
  FROM customer    -- <--- important: where the columns come from
)
SELECT customer_segment,
       COUNT(*) AS number_of_customers
FROM customer_type
GROUP BY customer_segment;

---	Q8 what are the top 3 most purchase product within each category?

WITH  item_counts  as (
select category,
itempurchased,
COUNT(customerid)as total_orders,
ROW_NUMBER() OVER (partition by category order by count(customerid)desc)as item_rank
from customer
group by category,itempurchased
)
select item_rank,category,itempurchased,total_orders
from item_counts
where item_rank<=3;

---Q9 are customer  who are repeat buyer (more then 5 previous purchases)also likely to subscribe?

select subscriptionstatus,
count(customerid)as repeat_buyer
from customer
where previouspurchases>5
group by subscriptionstatus

--Q10 what is the revenue contribution of each age group?

select age_group,
SUM(purchase_amount)as total_revenue
from customer 
group by age_group
order by total_revenue desc;
